# Taps
tap 'caskroom/cask'
tap 'buo/cask-upgrade'
tap 'homebrew/cask-versions'

# Casks - GUI
cask 'alfred'
cask 'amazon-chime'
cask 'authy'
cask 'caffeine'
cask 'intellij-idea'
cask 'keybase'
cask 'pritunl'
cask 'slack'

# Casks - CLI
cask 'iterm2'

# CLI Tools
brew 'tfenv'
brew 'awscli'
brew 'jq'
brew 'graphviz'

## OLD STUFF HERE
# tap 'homebrew/brewdler'
# tap 'homebrew/dupes'
# tap 'homebrew/versions'
# cask 'android-platform-tools'
# 
# # Dev Libraries
# brew 'gcc46'
# brew 'glib'
# 
# # Docker Tools
# brew 'docker'
# brew 'docker-compose', args: ['without-docker-machine']
# 
# # Kubernetes Tools
# cask 'minikube'
# brew 'docker-machine-driver-xhyve', args: ['without-docker-machine']
# brew 'kops'
# brew 'kubernetes-cli'
# 
# # CLI Tools
# brew 'csshx'
# brew 'hub'
# brew 'lastpass-cli', args: ['with-pinentry']
# brew 'reattach-to-user-namespace'
# brew 'thefuck'
# brew 'tmux'
# brew 'watch'
# brew 'wget'
# brew 'gpg'
# cask 'keybase'
# 
# # AWS Tools
# brew 'aws-shell'
# 
# # Go Tools
# brew 'go'
# brew 'godep'
# 

